spring:
  jackson:
    deserialization:
      fail-on-unknown-properties : true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

my-app:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@user.com
  user-password: user
  client-id: myApp
  client-secret: pass
